// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  player: string;
  'player-button': string;
  'player-content': string;
  playerButton: string;
  playerContent: string;
}
export const cssExports: CssExports;
export default cssExports;
