name: Build And Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm install

      - run: pnpm run compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
